services:
  server:
    build: ./server
    ports: ["5000:5000"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:5000/health"]  
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - net

  client:
    build: ./client
    environment:
      - TOTAL_REQS=1000
      - CONCURRENT_CLIENTS=100
      - EXPERIMENT_ID=exp1
    volumes:
      - ./data/logs:/app/output
    depends_on:
      server:
        condition: service_healthy
    networks:
      - net

  analyzer:  
    build: ./analyzer
    environment:
      - EXPERIMENT_ID=${EXPERIMENT_ID}
    volumes:
      - "./data/logs:/app/input"
      - "./results:/app/output"
    networks:
      - net
    depends_on:
      client:
        condition: service_completed_successfully

networks:
  net:
